[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NPM_VERSION = "6.5.0"
[[redirects]]
  from = "//hopeful-chandrasekhar-b6b82c.netlify.com/*"
  to = "//www.yo1000.com/:splat 301!"
