[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NPM_VERSION = "6.7.0"
[[redirects]]
  from = "https://yo1000.netlify.com"
  to = "https://www.yo1000.com"
  status = 301
  force = true
